---
spring:
  thymeleaf:
    enabled: "true "
    prefix: classpath:/templates/
    cache: "false"
    suffix: .html
  application:
    name: Working With File Walker

---
file-walker-list:
  fileWalkerDtos:
    -
      id: default
      startPath: /
      ignoredPaths:

---
http:
  host: "localhost"
  port: 9200

---
xpack:
  security:
    enabled: true

---
elastic:
  username: ""
  password: ""

---
bulkIngester:
  maxOperations: 1000
  flushInterval: 4

---
mediaTypeWorkflow:
  enabled: false
  esQuerySize: 1000
  threadCount: 5
  tikaPoolSize: 5

---
# spring pool size must be larger than the total number of threads being used inside the application
spring:
  task:
    scheduling:
      thread-name-prefix: "scheduling-"
      pool:
        size: 10