---
spring:
  thymeleaf:
    enabled: "true "
    prefix: classpath:/templates/
    cache: "false"
    suffix: .html
  application:
    name: Working With File Walker

---
file-walker-list:
  fileWalkerDtos:
    -
      id: default
      startPath: /
      ignoredPaths:

---
http:
  host: "localhost"
  port: 9200

---
xpack:
  security:
    enabled: true

---
elastic:
  username: ""
  password: ""

---
# Elasticsearch documentation about shard sizing:
# https://www.elastic.co/guide/en/elasticsearch/reference/7.17/size-your-shards.html#:~:text=There%20are%20no%20hard%20limits,your%20network%20and%20use%20case.
# Important: shard size should be between 10-50GB
esIndex:
  numberOfShards: 2
  numberOfReplicas: 0

---
bulkIngester:
  maxOperations: 1000
  flushInterval: 4
  maxConcurrentRequests: 1

---
mediaTypeWorkflow:
  enabled: false
  scheduledTaskFixedRate: 120000
  esQuerySize: 1000
  threadCount: 3
  tikaPoolSize: 3

---
scientificMetadataWorkflow:
  enabled: false
  scheduledTaskFixedRate: 120000
  esQuerySize: 1000

---
# spring pool size must be larger than the total number of threads being used inside the application
spring:
  task:
    scheduling:
      thread-name-prefix: "scheduling-"
      pool:
        size: 10